export const btn = "text-gray-50 p-2 rounded-full bg-green-600 shadow-black shadow-sm"
export const btnClassic="border rounded-md px-2 hover:bg-gray-300"
export const btnMenu = "bg-gray-50 hover:bg-green-600 hover:text-gray-50 hover:border hover:px-3 hover:border-gray-50 transition-all hover:animate-pulse text-green-600 px-4 rounded-full font-bold"
export const btnDelete = "bg-gray-50 hover:bg-red-600 hover:text-gray-50 border hover:border border-red-600 hover:border-gray-50 transition-all text-red-600 px-2 rounded-full font-bold"
export const btnEdit = "bg-gray-50 hover:bg-green-600 hover:text-gray-50 border hover:border border-green-600 hover:border-gray-50 transition-all text-green-600 px-2 rounded-full font-bold"
